language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace ReactiveKit.xcworkspace -scheme ReactiveKit-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test
